# Generated by Django 4.1.1 on 2022-09-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employee',
        ),
    ]
